SUPABASE_URL = "https://svexgvaaeeszdtsbggnf.supabase.co"
SUPABASE_API_KEY = "REDACTED_SUPABASE_KEY"

LINE_ACCESS_TOKENS = { hanbai = "2HY81RVT/kfV+dRWf3kza+T2VY9KvOkDTPMM7mJbuT6XelplCvtYtcETn8Ai0yAdx+QULuKRM89BDGlshRnOv36Sn4njldu9zGsP9xH1CS6u6hltevVRaAsA31gHVobTKoLN3XhWMXatrLRWb9nQEQdB04t89/1O/w1cDnyilFU=", seizou = "2HY81RVT/kfV+dRWf3kza+T2VY9KvOkDTPMM7mJbuT6XelplCvtYtcETn8Ai0yAdx+QULuKRM89BDGlshRnOv36Sn4njldu9zGsP9xH1CS6u6hltevVRaAsA31gHVobTKoLN3XhWMXatrLRWb9nQEQdB04t89/1O/w1cDnyilFU=" }
LINE_GROUP_IDS = { hanbai = "C5ee129dda8a376797df70b413d177f6b", seizou = "C4d2150d285597e54cc9b44c26403ac41", deadline = "C6064cf11799b7b22df0d5cb42417de19" }
